version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn config.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    expose:
      - "8000"
    env_file:
      - envs/production/.env.backend
    depends_on:
      - database
      - redis
    restart: always

  database:
    container_name: database
    image: postgres:16.0
    env_file:
      - envs/production/.env.db
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis:7.2.4
    expose:
      - "6379"
    command: sh -c "redis-server --save 60 1 --loglevel warning"
    restart: always

  nginx:
    container_name: nginx
    image: nginx:bookworm-perl
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/home/app/static
      - media:/home/app/media
    ports:
      - "80:80"
    restart: always

volumes:
  static:
  media:
  database:
