# Generated by Django 5.0.6 on 2024-05-30 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('shop', '0002_alter_productcategorymodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدید ها'},
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده'), (3, 'رد شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='reviewmodel',
            index=models.Index(fields=['-created_date'], name='review_revi_created_71d79e_idx'),
        ),
    ]
