# Generated by Django 5.0.6 on 2024-05-30 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('payment', '0002_alter_paymentmodel_options_and_more'),
        ('shop', '0002_alter_productcategorymodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'کوپن', 'verbose_name_plural': 'کوپن ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='useraddressmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AddIndex(
            model_name='couponmodel',
            index=models.Index(fields=['-created_date'], name='order_coupo_created_09df1f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemmodel',
            index=models.Index(fields=['-created_date'], name='order_order_created_f6d55d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['-created_date'], name='order_order_created_0ffabc_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddressmodel',
            index=models.Index(fields=['-created_date'], name='order_usera_created_6698f7_idx'),
        ),
    ]
