# Generated by Django 5.0.6 on 2024-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_footerlinkboxmodel_footerlinkmodel_slidermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='تصویر'),
        ),
    ]
