# Generated by Django 5.0.6 on 2024-05-30 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصویر محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='wishlistproductmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'لیست علاقه مندی محصول', 'verbose_name_plural': 'لیست علاقه مندی ها'},
        ),
        migrations.AddIndex(
            model_name='productcategorymodel',
            index=models.Index(fields=['-created_date'], name='shop_produc_created_67db60_idx'),
        ),
        migrations.AddIndex(
            model_name='productimagemodel',
            index=models.Index(fields=['-created_date'], name='shop_produc_created_0e2751_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['-created_date'], name='shop_produc_created_094b86_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistproductmodel',
            index=models.Index(fields=['-created_date'], name='shop_wishli_created_7a40dd_idx'),
        ),
    ]
