# Generated by Django 5.0.6 on 2024-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'لیست ارتباط با ما'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_date'], 'verbose_name': 'خبرنامه', 'verbose_name_plural': 'لیست خبرنامه'},
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['-created_date'], name='website_con_created_805101_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['-created_date'], name='website_new_created_3a65d7_idx'),
        ),
    ]
