# Generated by Django 5.0.6 on 2024-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactmodel_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
    ]
