# Generated by Django 5.0.6 on 2024-06-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contactmodel_content_alter_contactmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'لیست خبرنامه',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddIndex(
            model_name='newslettermodel',
            index=models.Index(fields=['-created_date'], name='website_new_created_c4803c_idx'),
        ),
    ]
