# Generated by Django 5.0.6 on 2024-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['-created_date'], name='payment_pay_created_e2e63d_idx'),
        ),
    ]
